### ISSUE TITLE
Frontend - saveLocalStorage

### ISSUE THREAD

**Issue by JDTheRipperPC** [JDTheRipperPC/Lunar-Lander-Teamwork#17]
Should be better just save the user credentials just when the login process is correct.
Now the credentials are saved even when an error on the login process occurs.

- [x] Move the saveLocalStorage into the success ajax method.

**Comment by SOSandreu1095** [comment]
Ok, I will modify it as soon as I can!
I will warn you and close the issue

**Comment by SOSandreu1095** [comment]
Done, it will be visible in the next push
