### ISSUE TITLE
Frontend - Coding standard

### ISSUE THREAD

**Issue by JDTheRipperPC** [JDTheRipperPC/Lunar-Lander-Teamwork#6]
- [x] Change TITLE tag content by something coherent (login.html)

- [x] Add META tag with description (index.html & login.html)

- [x] Change url param on ajax request, from "createUserServlet" to "CreateUserServlet"

- [x]  Insert a favicon to the web (index.html & login.html)

**Comment by SOSandreu1095** [comment]
Added a favicon too

**Comment by SOSandreu1095** [comment]
Should I change the url from "loginServlet" to "LoginServlet" too?

**Comment by JDTheRipperPC** [comment]
Favicon add it's nice. (Provisional icon)
Issue correctly resolved and closed.
