### ISSUE TITLE
Frontend - Validations in javascript

### ISSUE THREAD

**Issue by JDTheRipperPC** [JDTheRipperPC/Lunar-Lander-Teamwork#7]
- [x] Replace validation in javascript by html form input attributes (pattern, required, etc)

It's more efficient validate in html that in javascript.
I recommend change it to reduce the javascript code lines.

References:
https://www.w3schools.com/html/html_form_attributes.asp

**Comment by SOSandreu1095** [comment]
Done! However the default message will be in the native language of the browser. So it will display somthing like: 
"Completa el campo con las restricciones dadas:
_Minimum 4 characters"_

Furthermore, I implemented a custom Validation message via js / jquery, necesary to check that both passwords are the same

**Comment by JDTheRipperPC** [comment]
Issue correctly resolved and closed.
