### ISSUE TITLE
Frontend - Toast methods

### ISSUE THREAD

**Issue by JDTheRipperPC** [JDTheRipperPC/Lunar-Lander-Teamwork#8]
After check the javascript files I got some questions about the toast methods used in the login.html page.

- The .css and .js file that reference the toast must be hosted by us or can be linked from a server?

- There are defines many methods with similar parameters, can use an unique method with all the parameters needed to make the toast?

- Should be better don't repeat the documentation in each linea of the toast methods, should be possible resume all the parameters of the toast in an unique place?

**Comment by SOSandreu1095** [comment]
After check the javascript files I got some questions about the toast methods used in the login.html page.

- The .css and .js file that reference the toast must be hosted by us or can be linked from a server?
**_All I know is this: https://github.com/kamranahmedse/jquery-toast-plugin/ Here there is an explanation about How to use it? I didnt see any option about link it to other server, just 3 methods of install it, and I use the option of put it int our folders. Chech: HOW TO USE IT? In the link_**
- There are defines many methods with similar parameters, can use an unique method with all the parameters needed to make the toast?
**_Yes, I can change all to one method, specifying the kind of messasge, the submessage, the type of the toast, and the color (and more things if it is needed)_**

- Should be better don't repeat the documentation in each linea of the toast methods, should be possible resume all the parameters of the toast in an unique place?
**_I will change all to one method, with standard and fixed propieties and parameters that will change the toast (like I said in the 2nd point). And just having one method for the toogle_**

**Comment by SOSandreu1095** [comment]
All done! But it will change, because the validation will be in the html attributes. However now there are a single method that do all

**Comment by SOSandreu1095** [comment]
The commit is done, but i forgot to change the description of the commit, however, it is done

**Comment by JDTheRipperPC** [comment]
All the questions and code changes resolved.
Issue correctly resolved and closed.
